version: 2
general:
  branches:
    only:
      - master

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk-sid
    steps:
      - checkout
      - run: git config --local user.name 'authlib-injector Deploy Bot' && git config --local user.email 'authlib-injector-deploy-bot@yushi.moe'
      - run: ./.circleci/deploy-bmclapi.sh
